generator:
  class: sfDoctrineGenerator
  param:
    model_class:           category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ =name, created_at, updated_at ]
        title: Category management
      filter:  ~
      form:    ~
      edit:
        title: Editing category "%%name%%"
      new:
        title: New category
